### ISSUE TITLE
can't move downloaded files. 

### ISSUE THREAD

**Issue by Scottybegood** [PlexRipper/PlexRipper#346] opened 2024-09-21 07:23 UTC
I've Downloaded a movie and even after clearing it from the downloads list trying to rename the folder or file or move either results in this error messages: 
1: You need permission to perform this action.
2: The Action can't be completed because the folder or a file is open in another program

Is this just an unraid/docker permissions issue I misconfigured or is there something else going on that I'm failing to see?

**Comment by JasonLandbridge** [comment] 2024-09-28 10:01
I'm going to need some logs and way to reproduce because I'm not sure what you mean

**Comment by JasonLandbridge** [comment] 2024-10-04 12:02
Closing as duplicate: https://github.com/PlexRipper/PlexRipper/issues/208

**Closed as completed by JasonLandbridge** 2024-10-04 12:02 UTC
Labels: answer provided
