### ISSUE TITLE
[BUG] - Unable to download files that faulted mid way through download

### ISSUE THREAD

**Issue by Zekkz-stack** [PlexRipper/PlexRipper#335] opened 2024-08-15 20:42 UTC
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.20.0

### Platform

Unraid

### Browsers

Firefox

### Description

Seem to have an issue with some files that for whatever reason (Server crash, power down etc) were mid way interupted. Unable to get them started again.

Status on download will read as Error
Tried to delete PlexRipper, reinstall. Delete all files from AppData. 
Tried Safe New Perms
Changed folder placement.

Even with completely wiping PlexRipper from the Unraid server and cleansing left over folders. Rebooting inbtween in step. No change.

### Reproduction steps

```bash
1. Start download
2. Have the download stumble somehow.
3. Attempt to restart.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
21:23:39 [Debug] [GetAllPlexAccountsEndpoint.HandleAsync:50] => Returned 1 accounts

21:23:50 [Information] [ConfigManager.SaveConfig:135] => Saving user config settings now

21:23:50 [Information] [ConfigManager.SaveConfig:143] => UserSettings were saved successfully!

21:24:02 [Information] [ConfigManager.SaveConfig:135] => Saving user config settings now

21:24:02 [Information] [ConfigManager.SaveConfig:143] => UserSettings were saved successfully!

21:26:01 [Information] [StopDownloadTaskCommand.Handle:60] => Stopping [FOLDER]/[FILENAME]mkv from downloading

21:26:01 [Debug] [StopDownloadTaskCommand.Handle:69] => Deleting partially downloaded files of [FOLDER]/[FILENAME]mkv

21:26:02 [Information] [DownloadQueue.CheckDownloadQueue:60] => Adding 1 PlexServers to the DownloadQueue to check for the next download

21:26:02 [Debug] [DownloadQueue.CheckDownloadQueueServer:80] => Checking PlexServer: ***MASKED*** for the next download to start

21:26:02 [Information] [DownloadQueue.CheckDownloadQueueServer:98] => Selected download task [FOLDER]/[FILENAME]mkv to start as the next task

21:26:02 [Debug] [DownloadJob.Execute:45] => Executing job: DownloadJob for downloadTaskKey with id: DownloadTaskKey { Type = MovieData, Id = [STRING], PlexServerId = 3, PlexLibraryId = 7, IsValid = True, IsDownloadable = True }

21:26:02 [Debug] [DownloadJob.Execute:87] => Generated DownloadWorkerTasks for [FOLDER]/[FILENAME]mkv

21:26:02 [Debug] [DownloadJob.Execute:92] => Creating Download client for [FOLDER]/[FILENAME]mkv

21:26:02 [Debug] [PlexDownloadClient.Start:125] => Start downloading [FILENAME]mkv

21:26:02 [Debug] [DownloadWorker.Start:103] => Download worker with id: 33 start for filename: [FILENAME].part1.mkv

21:26:02 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:264] => Download worker 33 with [FILENAME].part1.mkv had an error!

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:265] => Could not create a download destination filestream for DownloadWorker with id 33
 - Metadata:
 -- DownloadWorkerId - 33

21:26:02 [Debug] [DownloadWorker.Start:103] => Download worker with id: 34 start for filename: [FILENAME].part2.mkv

21:26:02 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:264] => Download worker 34 with [FILENAME].part2.mkv had an error!

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:265] => Could not create a download destination filestream for DownloadWorker with id 34
 - Metadata:
 -- DownloadWorkerId - 34

21:26:02 [Debug] [DownloadWorker.Start:103] => Download worker with id: 35 start for filename: [FILENAME].part3.mkv

21:26:02 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:264] => Download worker 35 with [FILENAME].part3.mkv had an error!

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:265] => Could not create a download destination filestream for DownloadWorker with id 35
 - Metadata:
 -- DownloadWorkerId - 35

21:26:02 [Debug] [DownloadWorker.Start:103] => Download worker with id: 36 start for filename: [FILENAME].part4.mkv

21:26:02 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:264] => Download worker 36 with [FILENAME].part4.mkv had an error!

21:26:02 [Error] [DownloadWorker.SendDownloadWorkerError:265] => Could not create a download destination filestream for DownloadWorker with id 36
 - Metadata:
 -- DownloadWorkerId - 36

21:26:03 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:219] => DownloadTaskUpdate: [MovieData] [Error] [[FILENAME]mkv] [Download Location: /Downloads/]

21:26:03 [Debug] [DownloadJob.Execute:128] => Exiting job: DownloadJob for DownloadTaskGeneric with id: DownloadTaskKey { Type = MovieData, Id = [STRING], PlexServerId = 3, PlexLibraryId = 7, IsValid = True, IsDownloadable = True }

21:26:03 [Warning] [DownloadJob.Dispose:139] => Disposing job: DownloadJob for DownloadTaskGeneric

21:26:03 [Warning] [PlexDownloadClient.DisposeAsync:183] => PlexDownloadClient for DownloadTask with Id: [STRING] was disposed
```

**Comment by Zekkz-stack** [comment] 2024-08-15 20:43
I should also add, I had this issue on 0.19 too

**Comment by JasonLandbridge** [comment] 2024-08-15 20:45
Yo, at a quick glance it seems PlexRipper has no permission to create files in the directories you have mapped. Can you confirm that by going to Settings => Paths, that all paths are green llike this?

 
![Screenshot_20240815_224514](https://github.com/user-attachments/assets/47eee0cd-a09c-453f-91f2-beff0d976675)

**Comment by Zekkz-stack** [comment] 2024-08-15 20:47
Yeah I got green on all of those. 

![image](https://github.com/user-attachments/assets/ef64f7e6-13c6-4570-b609-3cf033616678)

Any file that I havent tried to download is perfectly fine. Just ones that were mid interupted.

**Comment by Zekkz-stack** [comment] 2024-08-15 20:49
It is also creating the new folder in prep to download, just errors as it starts to bring in the file itself.

Also tried bring the download chunks/segments down to one. does the same thing.

**Comment by JasonLandbridge** [comment] 2024-08-15 20:51
I see, then it might be a duplicate of this issue: https://github.com/PlexRipper/PlexRipper/issues/332

I will close this one now but rest assured that this is on my to-do list

**Closed as completed by JasonLandbridge** 2024-08-15 20:51 UTC
Labels: bug
