### ISSUE TITLE
CAN'T SORT MOVIES IN LIBRARY OR DOWNLOADS

### ISSUE THREAD

**Issue by alaska4life** [PlexRipper/PlexRipper#72] opened 2021-09-27 09:30 UTC
It would be nice if you can sort the columns by clicking on the columns.  Like title, year, size, etc.  Would be helpful to be able to sort.

**Comment by JasonLandbridge** [comment] 2021-09-27 10:09
Yes! This is a smaller feature which I hope to have implemented soon!

**Comment by JasonLandbridge** [comment] 2022-11-29 22:13
Closing this as it's a duplicate of #93

**Closed by JasonLandbridge** 2022-11-29 22:13 UTC
Labels: enhancement
