### ISSUE TITLE
[BUG] - Incomplete download file where the download process ends prematurely

### ISSUE THREAD

**Issue by prinler** [PlexRipper/PlexRipper#263] opened 2023-10-21 21:33 UTC
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.14.0

### Platform

Unraid

### Browsers

Google Chrome

### Description

Trying to download files from a plex server. I can see everything. When i click download it tried but only downloads 356 bytes and says its finished. Now, my log notifications in the top right show an error but when i click the bell, it shows nothing. It was working before and the issue says something about the downloader. "Downloadjob with DownloadJob.DownloadTaskId_XX cannot be stopped because it is not running"
"Directory: /Downloads/TvShows/nameofshow/Season 1/name of season/ does not exsist"
Filepath: /Downloads/TvShows/nameofshow/season 1/name of season/nameofepisode1.mkv does not exsist and cannot be used to merge/move the file!"
I have checked to ensure the paths are right, it makes the folders... the permissions are right... Im at a loss. 

### Reproduction steps

```bash
Click on a remote plex server, try and download a file and watch it only download 365byes and say its complete.
```

### Screenshots

```bash
https://paste.pics/POOGQ
```

### Logs

```bash
14:13:17 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

14:13:17 [Debug] [DownloadWorker.Start:108] => Download worker with id: 14 start for filename: Erin Brockovich (2000) Bluray-1080p.part2.mkv

14:13:17 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

14:13:17 [Debug] [DownloadWorker.Start:108] => Download worker with id: 15 start for filename: Erin Brockovich (2000) Bluray-1080p.part3.mkv

14:13:17 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

14:13:17 [Debug] [DownloadWorker.Start:108] => Download worker with id: 16 start for filename: Erin Brockovich (2000) Bluray-1080p.part4.mkv

14:13:17 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 13 and with filename: Erin Brockovich (2000) Bluray-1080p.part1.mkv changed status to Downloading

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 13 and with filename: Erin Brockovich (2000) Bluray-1080p.part1.mkv changed status to DownloadFinished

14:13:17 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 13 with Erin Brockovich (2000) Bluray-1080p.part1.mkv finished!

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 16 and with filename: Erin Brockovich (2000) Bluray-1080p.part4.mkv changed status to Downloading

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 16 and with filename: Erin Brockovich (2000) Bluray-1080p.part4.mkv changed status to DownloadFinished

14:13:17 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 16 with Erin Brockovich (2000) Bluray-1080p.part4.mkv finished!

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 15 and with filename: Erin Brockovich (2000) Bluray-1080p.part3.mkv changed status to Downloading

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 15 and with filename: Erin Brockovich (2000) Bluray-1080p.part3.mkv changed status to DownloadFinished

14:13:17 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 15 with Erin Brockovich (2000) Bluray-1080p.part3.mkv finished!

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 14 and with filename: Erin Brockovich (2000) Bluray-1080p.part2.mkv changed status to Downloading

14:13:17 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 14 and with filename: Erin Brockovich (2000) Bluray-1080p.part2.mkv changed status to DownloadFinished

14:13:17 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 14 with Erin Brockovich (2000) Bluray-1080p.part2.mkv finished!

14:13:18 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:217] => [File: Erin Brockovich (2000) Bluray-1080p.mkv - Status: DownloadFinished] - (13 - 0 ) + (14 - 0 ) + (15 - 0 ) + (16 - 0 ) = ( - 0)

14:13:18 [Debug] [FileMergeScheduler.CreateFileTaskFromDownloadTask:33] => Adding DownloadTask Erin Brockovich with id 1 to a FileTask to be merged

14:13:18 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download

14:13:18 [Debug] [DownloadJob.Execute:141] => Exiting job: DownloadJob for DownloadTask with id: 1

14:13:18 [Debug] [FileMergeJob.Execute:51] => Executing job: FileMergeJob for fileTaskId with id: 5

14:13:18 [Information] [FileMergeJob.Execute:68] => Executing FileMergeJob with name Erin Brockovich (2000) Bluray-1080p.mkv and id 5

14:13:18 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start

14:13:18 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Erin Brockovich (2000) to start as the next task

14:13:18 [Warning] [DownloadTaskScheduler.StartDownloadTaskJob:31] => DownloadJob with DownloadJob.DownloadTaskId_1 already exists

14:13:18 [Debug] [FileMergeJob.Execute:115] => Starting file merge process for 4 parts into a file Erin Brockovich (2000) Bluray-1080p.mkv

14:13:18 [Warning] [DownloadJob.Dispose:152] => Disposing job: DownloadJob for DownloadTask

14:13:18 [Warning] [PlexDownloadClient.DisposeAsync:170] => PlexDownloadClient for DownloadTask with Id: 1 was disposed

14:13:18 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part1.mkv has been merged into the single media file

14:13:18 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part1.mkv since it has been merged already

14:13:19 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part2.mkv has been merged into the single media file

14:13:19 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part2.mkv since it has been merged already

14:13:19 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part3.mkv has been merged into the single media file

14:13:19 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part3.mkv since it has been merged already

14:13:20 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part4.mkv has been merged into the single media file

14:13:20 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/Movies/Erin Brockovich (2000)/Erin Brockovich (2000) Bluray-1080p.part4.mkv since it has been merged already

14:13:21 [Information] [FileMergeJob.Execute:133] => Finished combining 4 files into Erin Brockovich (2000) Bluray-1080p.mkv

14:13:36 [Debug] [FileSystem.LookupContents:123] => Looking up path: null

14:13:38 [Debug] [FileSystem.LookupContents:123] => Looking up path: /

14:13:40 [Debug] [FileSystem.LookupContents:123] => Looking up path: /Movies/

14:13:44 [Debug] [DeleteFolderPathCommandHandler.Handle:30] => Deleted FolderPath with Id: 15 from the database

14:13:46 [Debug] [FileSystem.LookupContents:123] => Looking up path: /Downloads
```

**Comment by JasonLandbridge** [comment] 2023-11-12 19:37
This might be a duplicate of: https://github.com/PlexRipper/PlexRipper/issues/251

**Comment by pelisdev** [comment] 2023-12-17 04:33
Any news about this issue? It still getting that bug

**Comment by JasonLandbridge** [comment] 2024-08-06 14:15
Due to the age of this issue I'm closing it as a big update ([0.15-0.17](https://github.com/PlexRipper/PlexRipper/releases)) with a years worth of updates and fixes has been released. Please let me know if this is still an issue!

**Closed by JasonLandbridge** 2024-08-06 14:15 UTC
Labels: bug, Needs investigation
