### ISSUE TITLE
no download button

### ISSUE THREAD

**Issue by gerberanub** [PlexRipper/PlexRipper#283] opened 2023-11-30 16:34 UTC
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.14.0

### Platform

Synology

### Browsers

Google Chrome

### Description

i installed this and synched my plex account. but i cant find download button anywhere ?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 
01:16:10 [Debug] [PlexLibraryService.RefreshPlexTvShowLibrary:152] => Finished retrieving all media for library ***MASKED*** in 000 seconds

01:16:10 [Debug] [CreateUpdateOrDeletePlexTvShowsCommandHandler.Handle:43] => Starting adding, updating or deleting of tv shows in library: ***MASKED*** with id:  30

01:16:10 [Information] [CreateUpdateOrDeletePlexTvShowsCommandHandler.Handle:189] => Finished updating plexLibrary: ***MASKED*** with id: 30 in 0.2721631 seconds

01:16:10 [Debug] [PlexLibraryService.RefreshPlexTvShowLibrary:168] => Finished updating all media in the database for library ***MASKED*** in 000 seconds

01:16:10 [Debug] [PlexApi.GetLibrarySectionsAsync:141] => GetLibrarySectionsAsync => http://***MASKED***/library/sections

01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:10 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:11 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: 

01:16:11 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: "http://111.111.111.111:1500/library/sections/85/all?X-Plex-Token=xxxxxxxxxxxxxxxxxxxxxx-Plex-Container-Start=0&X-Plex-Container-Size=5000&type=4"

01:16:11 [Debug] [PlexLibraryService.RefreshPlexTvShowLibrary:152] => Finished retrieving all media for library ***MASKED*** in 001 seconds

01:16:12 [Debug] [CreateUpdateOrDeletePlexTvShowsCommandHandler.Handle:43] => Starting adding, updating or deleting of tv shows in library: ***MASKED*** with id:  31

01:16:12 [Information] [CreateUpdateOrDeletePlexTvShowsCommandHandler.Handle:189] => Finished updating plexLibrary: ***MASKED*** with id: 31 in 0.3311038 seconds

01:16:12 [Debug] [PlexLibraryService.RefreshPlexTvShowLibrary:168] => Finished updating all media in the database for library ***MASKED*** in 001 seconds

01:16:12 [Information] [SyncServerJob.Execute:108] => Successfully synced server "***MASKED***" with id 1 has no libraries to sync

01:19:18 [Debug] [PlexAccountService.GetAllPlexAccountsAsync:172] => Returning all PlexAccounts

01:19:18 [Debug] [PlexAccountController.GetAllAccounts:38] => Returned 1 accounts
```

**Comment by frosit** [comment] 2024-01-09 23:58
Well, it seems like it did fetch libraries and media and so on based on your log but since you didn't really provide reproduction steps... or a screenshot... or any other useful info I cannot really help you.

My only suggestion is that big libraries take a while to load as this solution pulls in all data of the library so if you have a few TB of content, it's going to take a while for things to appear. You should provide more info, more screenshots, what is configured, do you see media content at all? etc.. etc..

@JasonLandbridge we should fix our issue templates.

@gerberanub will close this one, if you still need help. please be more detailed and make a new request.

**Closed by frosit** 2024-01-09 23:58 UTC
Labels: bug
